version: '3.1'

services:
  pg11:
    build: .
    restart: always
    env_file:
      - ./pg_docker.env
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: thajeztah/pgadmin4
    restart: always
    ports:
        - '5050:5050'
    volumes:
        - pgadmin:/pgadmin

volumes:
    pgdata:
    pgadmin:

