version: '3.1'

services:
  pgdb:
    build: .
    restart: always
    env_file:
      - ./pg_docker.env
    ports:
        - '5432:5432'
    volumes:
        - pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest 
    restart: always
    env_file:
      - ./pgadmin.env
    ports:
        - '5050:80'
    volumes:
        - pgadmin:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin:

